apiVersion: cbt.storage.k8s.io/v1alpha1
kind: SnapshotMetadataService
metadata:
  generateName: csi-hostpath-
  labels:
    cbt.storage.k8s.io/driver: hostpath.csi.k8s.io
spec:
  address: external-snapshot-metadata.csi-driver:6443
  caCert: GENERATED_CA_CERT
  audiences:
  - 005e2583-91a3-4850-bd47-4bf32990fd00
